name: phidl
channels:
  - enneamer
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2018.11.29
  - cairo=1.14.6
  - certifi=2018.11.29
  - cffi=1.11.5
  - cython=0.29.3
  - decorator=4.3.2
  - ete3=3.1.1
  - fire=0.1.3
  - fontconfig=2.12.1
  - freetype=2.7
  - future=0.17.1
  - gettext=0.19.8.1
  - glib=2.51.4
  - graphite2=1.3.13
  - harfbuzz=1.4.3
  - hyperopt=0.1.1
  - icu=58.2
  - intel-openmp=2019.1
  - jpeg=9c
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - logbook=1.4.1
  - lxml=4.3.0
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - networkx=2.2
  - ninja=1.8.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - pango=1.40.4
  - pcre=8.41
  - pip=18.1
  - pixman=0.34.0
  - pthread-stubs=0.4
  - pycparser=2.19
  - pymongo=3.7.1
  - pyqt=4.11.4
  - python=3.6.7
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - pyyaml=3.13
  - qt=4.8.7
  - readline=7.0
  - scipy=1.1.0
  - setuptools=40.6.3
  - sip=4.18
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.9
  - wheel=0.32.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.6
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - adabound==0.0.5
